# Generated by Django 4.0.4 on 2022-04-15 09:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0003_neighborhood_doctor_no_neighborhood_police_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default=True, max_length=255, verbose_name='image'),
        ),
    ]
