# Generated by Django 4.0.4 on 2022-04-15 10:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0004_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='image_hood',
            field=cloudinary.models.CloudinaryField(default=True, max_length=255, verbose_name='image'),
        ),
    ]
