# Generated by Django 4.0.4 on 2022-04-15 13:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0006_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
