# Generated by Django 4.0.4 on 2022-04-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0008_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['-pk']},
        ),
    ]
