# Generated by Django 4.0.4 on 2022-04-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0009_alter_business_options_alter_neighborhood_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
